# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16nIqQWpbr-SO1gbQTsSHuz0_RPPXFqAn
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import butter, filtfilt

# %matplotlib inline

fs = 100
duration = 10
t = np.arange(0, duration, 1/fs)

trend = 0.5 * t + 2
high_freq = 1.5 * np.sin(2*np.pi*30*t)
noise = np.random.normal(0, 0.5, size=len(t))

signal = trend + high_freq + noise

df = pd.DataFrame({"t": t, "signal": signal})
mean_signal = df["signal"].mean()
print("Mean of signal:", mean_signal)
print(df.head())

coeffs = np.polyfit(df["t"], df["signal"], 1)
slope, intercept = coeffs
print("Slope:",slope)
print("Intercept:", intercept)
df["trend"] = slope * df["t"] + intercept

def lowpass(data, cutoff, fs, order=4):
    nyq = 0.5 * fs
    normal_cutoff = cutoff / nyq
    b, a = butter(order, normal_cutoff, btype="low")
    return filtfilt(b, a, data)

df["filtered"] = lowpass(df["signal"], cutoff=5, fs=fs)

plt.figure(figsize=(10,5))
plt.plot(df["t"], df["signal"], label="raw", alpha=0.4)
plt.plot(df["t"], df["trend"], label="trend", linewidth=3)
plt.plot(df["t"], df["filtered"], label="filtered", linewidth=2)
plt.legend()
plt.xlabel("Time (s)")
plt.ylabel("Value")
plt.grid()
plt.show()